-- Migration: Add New Modules (Dashboard, Meta Ads V2, Billing, IA Logs)
-- This migration was generated by comparing the Blackback original project with the Feb 20th backup.

-- 1. Meta Ads V2 Module
CREATE TABLE IF NOT EXISTS public.meta_connections (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    meta_user_id text NOT NULL,
    meta_user_name text,
    email text,
    picture_url text,
    access_token text,
    token_expires_at timestamp with time zone,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.meta_business_managers (
    id text PRIMARY KEY,
    name text NOT NULL,
    connection_id uuid REFERENCES public.meta_connections(id) ON DELETE CASCADE,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.meta_ad_accounts (
    account_id text PRIMARY KEY,
    organization_id uuid REFERENCES public.organizations(id) ON DELETE CASCADE,
    name text NOT NULL,
    currency text,
    timezone text,
    connection_id uuid REFERENCES public.meta_connections(id) ON DELETE CASCADE,
    business_manager_id text REFERENCES public.meta_business_managers(id) ON DELETE SET NULL,
    status text DEFAULT 'ACTIVE',
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.meta_campaigns (
    campaign_id text PRIMARY KEY,
    account_id text NOT NULL,
    name text,
    objective text,
    status text,
    buying_type text,
    updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.meta_ad_sets (
    adset_id text PRIMARY KEY,
    campaign_id text NOT NULL REFERENCES public.meta_campaigns(campaign_id) ON DELETE CASCADE,
    name text,
    status text,
    daily_budget numeric,
    targeting jsonb,
    updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.meta_ads (
    ad_id text PRIMARY KEY,
    adset_id text NOT NULL REFERENCES public.meta_ad_sets(adset_id) ON DELETE CASCADE,
    name text,
    status text,
    creative jsonb,
    updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.meta_insights (
    ad_id text NOT NULL REFERENCES public.meta_ads(ad_id) ON DELETE CASCADE,
    date date NOT NULL,
    account_id text NOT NULL,
    campaign_id text NOT NULL,
    adset_id text NOT NULL,
    spend numeric DEFAULT 0,
    impressions bigint DEFAULT 0,
    clicks bigint DEFAULT 0,
    reach bigint DEFAULT 0,
    actions jsonb DEFAULT '{}'::jsonb,
    action_values jsonb DEFAULT '{}'::jsonb,
    updated_at timestamp with time zone DEFAULT now(),
    PRIMARY KEY (ad_id, date)
);

-- 2. Dashboard Module
CREATE TABLE IF NOT EXISTS public.manager_dashboard_widgets (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    organization_id uuid REFERENCES public.organizations(id) ON DELETE CASCADE,
    profile_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
    widget_type text NOT NULL,
    config jsonb,
    position_x integer,
    position_y integer,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.organization_stats (
    organization_id uuid PRIMARY KEY REFERENCES public.organizations(id) ON DELETE CASCADE,
    total_clients integer DEFAULT 0,
    active_projects integer DEFAULT 0,
    pending_tasks integer DEFAULT 0,
    storage_used bigint DEFAULT 0,
    updated_at timestamp with time zone DEFAULT now()
);

-- 3. Billing Module
CREATE TABLE IF NOT EXISTS public.subscriptions (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    plan text NOT NULL,
    status text NOT NULL,
    billing_value numeric,
    contracted_clients integer DEFAULT 0,
    max_users integer,
    asaas_customer_id text,
    asaas_subscription_id text,
    current_period_end timestamp with time zone,
    trial_ends_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.invoices (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    organization_id uuid REFERENCES public.organizations(id) ON DELETE CASCADE,
    subscription_id uuid REFERENCES public.subscriptions(id) ON DELETE SET NULL,
    amount numeric,
    client_count integer,
    status text,
    due_date timestamp with time zone,
    paid_at timestamp with time zone,
    asaas_payment_id text,
    asaas_invoice_url text,
    asaas_boleto_url text,
    asaas_pix_code text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

-- 4. IA and Marketing Support Module
CREATE TABLE IF NOT EXISTS public.ai_usage_logs (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    agent_id uuid NOT NULL,
    timestamp timestamp with time zone DEFAULT now(),
    model text,
    tokens_input integer DEFAULT 0,
    tokens_output integer DEFAULT 0,
    cost_usd double precision DEFAULT 0,
    context jsonb DEFAULT '{}'::jsonb,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.workers_ia_funnel_stages (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    agent_id uuid REFERENCES public.workers_ia_agents(id) ON DELETE CASCADE,
    stage_key text NOT NULL,
    label text,
    color text,
    bg text,
    border text,
    position integer
);

CREATE TABLE IF NOT EXISTS public.marketing_manual_metrics (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    organization_id uuid NOT NULL REFERENCES public.organizations(id) ON DELETE CASCADE,
    client_id uuid NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE,
    date date NOT NULL,
    channel text NOT NULL,
    leads integer DEFAULT 0,
    investment numeric(15,2) DEFAULT 0,
    conversions integer DEFAULT 0,
    revenue numeric(15,2) DEFAULT 0,
    updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.tintim_config (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    client_id uuid NOT NULL REFERENCES public.clients(id) ON DELETE CASCADE,
    "apiKey" text,
    "funnelId" text,
    "stageId" text,
    "customFields" jsonb DEFAULT '{}'::jsonb,
    "isActive" boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

-- Row Level Security (RLS)

-- 1. Meta Connections
ALTER TABLE public.meta_connections ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view connections in their organization" ON public.meta_connections
    FOR SELECT USING (organization_id = (SELECT organization_id FROM public.profiles WHERE id = auth.uid()));
CREATE POLICY "Users can insert/update connections in their organization" ON public.meta_connections
    FOR ALL USING (organization_id = (SELECT organization_id FROM public.profiles WHERE id = auth.uid()));

-- 2. Meta Business Managers
ALTER TABLE public.meta_business_managers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view BMs in their organization" ON public.meta_business_managers
    FOR SELECT USING (connection_id IN (SELECT id FROM public.meta_connections WHERE organization_id = (SELECT organization_id FROM public.profiles WHERE id = auth.uid())));
CREATE POLICY "Users can manage BMs in their organization" ON public.meta_business_managers
    FOR ALL USING (connection_id IN (SELECT id FROM public.meta_connections WHERE organization_id = (SELECT organization_id FROM public.profiles WHERE id = auth.uid())));

-- 3. Meta Ad Accounts
ALTER TABLE public.meta_ad_accounts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view Ad Accounts in their organization" ON public.meta_ad_accounts
    FOR SELECT USING (organization_id = (SELECT organization_id FROM public.profiles WHERE id = auth.uid()));
CREATE POLICY "Users can manage Ad Accounts in their organization" ON public.meta_ad_accounts
    FOR ALL USING (organization_id = (SELECT organization_id FROM public.profiles WHERE id = auth.uid()));

-- 4. Dashboard Widgets
ALTER TABLE public.manager_dashboard_widgets ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all for manager_dashboard_widgets" ON public.manager_dashboard_widgets FOR ALL USING (true);

-- 5. Organization Stats
ALTER TABLE public.organization_stats ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all for organization_stats" ON public.organization_stats FOR ALL USING (true);

-- 6. Subscriptions and Invoices
ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all for subscriptions" ON public.subscriptions FOR ALL USING (true);
CREATE POLICY "Users can view subscriptions in their organization" ON public.subscriptions
    FOR SELECT USING (organization_id IN (SELECT organization_id FROM public.team_members WHERE profile_id = auth.uid()));

ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all for invoices" ON public.invoices FOR ALL USING (true);
CREATE POLICY "Users can view invoices in their organization" ON public.invoices
    FOR SELECT USING (organization_id IN (SELECT organization_id FROM public.team_members WHERE profile_id = auth.uid()));

-- 7. Marketing Manual Metrics
ALTER TABLE public.marketing_manual_metrics ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all for same organization" ON public.marketing_manual_metrics
    FOR ALL USING (EXISTS (SELECT 1 FROM public.team_members tm WHERE tm.organization_id = public.marketing_manual_metrics.organization_id AND tm.profile_id = auth.uid()));

-- 8. TinTim Config
ALTER TABLE public.tintim_config ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all for same organization" ON public.tintim_config
    FOR ALL USING (EXISTS (SELECT 1 FROM public.clients c JOIN public.team_members tm ON tm.organization_id = c.organization_id WHERE c.id = public.tintim_config.client_id AND tm.profile_id = auth.uid()));

-- 9. Workers IA Funnel Stages
ALTER TABLE public.workers_ia_funnel_stages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all for workers_ia_funnel_stages" ON public.workers_ia_funnel_stages FOR ALL USING (true);
